### ISSUE TITLE
Doesn't allow named parameters in base url?

### ISSUE THREAD

**Issue by Madd0g** [APIs-guru/raml-to-swagger#2]
I tried running this RAML through the converter:

https://github.com/raml-apis/WeatherUnderground/blob/master/wunderground.raml

The converter asserts that there's no `{` in the URL, but it has an `{api_key}` in the url, is there anything that can be done about that?

**Comment by IvanGoncharov** [comment]
problem is in this line:

``` yaml
baseUri: http://api.wunderground.com/api/{api_key}
```

Swagger doesn't support template parameter in `baseUrl`.
So the only possible solution would be to add `api_key` as a template argument to every endpoint.
Will try to implement this fix in a next few days.

BTW. Did you check is `wunderground.raml` up to date or not?
It was written a few years ago and wasn't updated since.
I'm interested in adding it into our collection of specs:
https://github.com/APIs-guru/api-models

**Comment by Madd0g** [comment]
Moving the template param to the paths sounds like a good solution. Thanks

I did not check if the RAML is updated. It was just the only one I found.

**Comment by IvanGoncharov** [comment]
@Madd0g Fixed in `1.1.0`.
